#!/usr/bin/env python3
"""Generate Rust static font tables from AGL, pdf.js encodings, and Core14 metrics.

Outputs committed Rust source (no build-time network) into the crate's
pdf/tables/ directory.
"""
import re
import sys
from pathlib import Path

DATA = Path(__file__).parent
OUT = Path(sys.argv[1])  # crate src/pdf/tables dir
OUT.mkdir(parents=True, exist_ok=True)

HEADER = "// @generated by tools/gen_font_tables (from AGL + pdf.js). Do not edit by hand.\n\n"


def rust_str(codepoints):
    """A sequence of ints -> a Rust string literal using \\u{..} escapes."""
    return '"' + "".join(f"\\u{{{c:04X}}}" for c in codepoints) + '"'


# ---- 1. Adobe Glyph List: name -> unicode string ----
def gen_agl():
    entries = []
    for line in (DATA / "glyphlist.txt").read_text().splitlines():
        if line.startswith("#") or ";" not in line:
            continue
        name, codes = line.split(";", 1)
        cps = [int(h, 16) for h in codes.split()]
        entries.append((name, cps))
    entries.sort(key=lambda e: e[0])
    lines = [HEADER, "/// Adobe Glyph List: glyph name -> Unicode string (sorted by name).\n"]
    lines.append(f"pub static AGL: &[(&str, &str)] = &[\n")
    for name, cps in entries:
        lines.append(f'    ("{name}", {rust_str(cps)}),\n')
    lines.append("];\n")
    (OUT / "agl.rs").write_text("".join(lines))
    return len(entries)


# ---- 2. Base encodings: code -> glyph name ([&str; 256]) ----
def parse_encoding(js, const_name):
    m = re.search(r"const %s = \[(.*?)\];" % const_name, js, re.S)
    if not m:
        return None
    names = re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(1))
    names = (names + [""] * 256)[:256]
    return names


def gen_encodings():
    js = (DATA / "encodings.js").read_text()
    wanted = {
        "STANDARD": "StandardEncoding",
        "WIN_ANSI": "WinAnsiEncoding",
        "MAC_ROMAN": "MacRomanEncoding",
        "ZAPF_DINGBATS": "ZapfDingbatsEncoding",
    }
    lines = [HEADER, "/// Base encodings: byte code -> glyph name (\"\" = undefined).\n"]
    count = 0
    for rust_name, js_name in wanted.items():
        names = parse_encoding(js, js_name)
        if names is None:
            print(f"  WARN: encoding {js_name} not found", file=sys.stderr)
            continue
        count += 1
        lines.append(f"pub static {rust_name}: [&str; 256] = [\n")
        for i in range(0, 256, 8):
            row = ", ".join(f'"{n}"' for n in names[i : i + 8])
            lines.append(f"    {row},\n")
        lines.append("];\n\n")
    (OUT / "encodings.rs").write_text("".join(lines))
    return count


# ---- 3. Core14 metrics: (font, glyph name) -> width ----
STD14_FONTS = [
    "Helvetica", "Helvetica-Bold", "Helvetica-Oblique", "Helvetica-BoldOblique",
    "Times-Roman", "Times-Bold", "Times-Italic", "Times-BoldItalic",
    "Symbol", "ZapfDingbats",
]


def gen_metrics():
    js = (DATA / "metrics.js").read_text().splitlines()
    fonts = {}          # font -> list[(glyph, width)]
    courier = {}        # font -> constant width
    current = None
    start_re = re.compile(r'^  t(?:\.([A-Za-z0-9-]+)|\["([^"]+)"\]) = getLookupTableFactory')
    const_re = re.compile(r'^  t(?:\.([A-Za-z0-9-]+)|\["([^"]+)"\]) = (\d+);')
    glyph_re = re.compile(r'^    t(?:\.([A-Za-z0-9._]+)|\["([^"]+)"\]) = (\d+);')
    end_re = re.compile(r'^  \}\);')
    for line in js:
        ms = start_re.match(line)
        if ms:
            current = ms.group(1) or ms.group(2)
            fonts[current] = []
            continue
        if current:
            mg = glyph_re.match(line)
            if mg:
                fonts[current].append((mg.group(1) or mg.group(2), int(mg.group(3))))
                continue
            if end_re.match(line):
                current = None
                continue
        mc = const_re.match(line)
        if mc:
            courier[mc.group(1) or mc.group(2)] = int(mc.group(3))

    lines = [HEADER, "// Core-14 font metrics: glyph name -> advance width (1/1000 em).\n\n"]
    # Monospace (Courier family): a single constant.
    lines.append("/// Courier family is monospace at this width.\n")
    lines.append(f"pub const COURIER_WIDTH: u16 = {courier.get('Courier', 600)};\n\n")
    emitted = ["COURIER_WIDTH"]
    for font in STD14_FONTS:
        table = fonts.get(font)
        if not table:
            print(f"  WARN: metrics for {font} not found", file=sys.stderr)
            continue
        table = sorted(set(table), key=lambda e: e[0])
        rust_name = font.upper().replace("-", "_")
        emitted.append(rust_name)
        lines.append(f"pub static {rust_name}: &[(&str, u16)] = &[\n")
        for glyph, w in table:
            lines.append(f'    ("{glyph}", {w}),\n')
        lines.append("];\n\n")
    # A lookup dispatch by base font name.
    lines.append("/// Metrics table for a standard-14 base font name, if known.\n")
    lines.append("pub fn std14_metrics(base: &str) -> Option<&'static [(&'static str, u16)]> {\n")
    lines.append("    match base {\n")
    for font in STD14_FONTS:
        if font.upper().replace("-", "_") in emitted:
            lines.append(f'        "{font}" => Some({font.upper().replace("-", "_")}),\n')
    lines.append("        _ => None,\n    }\n}\n")
    (OUT / "metrics.rs").write_text("".join(lines))
    return emitted


def main():
    n_agl = gen_agl()
    n_enc = gen_encodings()
    emitted = gen_metrics()
    mod = HEADER + "pub mod agl;\npub mod encodings;\npub mod metrics;\n"
    (OUT / "mod.rs").write_text(mod)
    print(f"AGL entries: {n_agl}")
    print(f"encodings emitted: {n_enc}")
    print(f"metrics emitted: {emitted}")


main()
